package cn.lut.schedule.tests;
import android.app.Activity;
import android.app.Instrumentation;
import android.app.NotificationManager;
import android.app.job.JobScheduler;
import android.app.job.JobInfo;
import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import org.json.JSONObject;
import org.json.JSONArray;
import java.lang.reflect.*;
import java.io.File;
import java.io.FileOutputStream;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

/** Synthetic data integration tests. No school account or school records are used. */
public final class RuntimeV016 {
    private final Instrumentation test;private int checks;
    RuntimeV016(Instrumentation test){this.test=test;}
    private void check(boolean value,String reason){checks++;if(!value)throw new AssertionError(reason);}
    private Object field(Object target,String name)throws Exception{Field f=target.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(target);}
    private Object call(Object target,String name,Class<?>[] types,Object... args)throws Exception{Method m=target instanceof Class?((Class<?>)target).getDeclaredMethod(name,types):target.getClass().getDeclaredMethod(name,types);m.setAccessible(true);return m.invoke(target instanceof Class?null:target,args);}
    private void main(Runnable task){test.runOnMainSync(task);test.waitForIdleSync();}
    private void invokeMain(Object target,String method,Class<?>[] types,Object... args){main(()->{try{call(target,method,types,args);}catch(Exception e){throw new RuntimeException(e);}});}
    private View text(View view,String value){if(view instanceof android.widget.TextView&&((android.widget.TextView)view).getText().toString().equals(value))return view;if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++){View hit=text(group.getChildAt(i),value);if(hit!=null)return hit;}}return null;}
    private View described(View view,String value){if(value.equals(String.valueOf(view.getContentDescription())))return view;if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++){View hit=described(group.getChildAt(i),value);if(hit!=null)return hit;}}return null;}
    private void capture(String name)throws Exception{test.waitForIdleSync();Thread.sleep(300);android.graphics.Bitmap bitmap=test.getUiAutomation().takeScreenshot();try(FileOutputStream out=new FileOutputStream(new File(test.getTargetContext().getExternalFilesDir(null),name))){bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();}
    private void stop(Activity activity)throws Exception{invokeMain(Class.forName("cn.lut.schedule.Diagnostics"),"detach",new Class<?>[]{activity.getClass()},activity);invokeMain(field(activity,"coordinator"),"close",new Class<?>[0]);Object dialog=field(activity,"loginDialog");if(dialog!=null)main(()->((android.app.Dialog)dialog).dismiss());((android.os.Handler)field(activity,"handler")).removeCallbacksAndMessages(null);}
    private JSONObject fixture(Activity activity,String kind,String html)throws Exception{Class<?> reader=Class.forName("cn.lut.schedule.AcademicReader"),callback=Class.forName("cn.lut.schedule.AcademicReader$Callback");Method read=reader.getDeclaredMethod("read",WebView.class,String.class,callback);read.setAccessible(true);CountDownLatch ready=new CountDownLatch(1);JSONObject[] answer={null};Throwable[] error={null};WebView[] web={null};Object proxy=Proxy.newProxyInstance(callback.getClassLoader(),new Class<?>[]{callback},(p,m,args)->{answer[0]=(JSONObject)args[0];error[0]=(Throwable)args[1];ready.countDown();return null;});
        main(()->{web[0]=new WebView(activity);web[0].getSettings().setJavaScriptEnabled(true);((ViewGroup)activity.getWindow().getDecorView()).addView(web[0],new ViewGroup.LayoutParams(1,1));web[0].setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String url){try{read.invoke(null,v,kind,proxy);}catch(Exception e){error[0]=e;ready.countDown();}}});web[0].loadDataWithBaseURL("https://jwxt.lut.edu.cn/test-academic",html,"text/html","UTF-8",null);});check(ready.await(10,TimeUnit.SECONDS),"academic fixture timeout");main(()->{((ViewGroup)web[0].getParent()).removeView(web[0]);web[0].destroy();});if(error[0]!=null)throw new AssertionError(error[0]);return answer[0];}
    private JSONObject grade(String score,boolean second)throws Exception{JSONObject result=new JSONObject();result.put("kind","grades");result.put("complete",true);JSONArray rows=new JSONArray();rows.put(new JSONObject().put("key","2026|math").put("name","测试数学").put("score",score));if(second)rows.put(new JSONObject().put("key","2026|english").put("name","测试英语").put("score","95"));result.put("records",rows);return result;}
    public String run(Activity activity)throws Exception{
        stop(activity);Class<?>[] none=new Class<?>[0];Object initialStore=field(activity,"academicStore");call(initialStore,"clear",none);invokeMain(activity,"loadAcademic",none);NotificationManager resetManager=(NotificationManager)activity.getSystemService(Context.NOTIFICATION_SERVICE);resetManager.cancelAll();for(int wait=0;wait<30&&resetManager.getActiveNotifications().length!=0;wait++)Thread.sleep(100);activity.getSharedPreferences("settings",0).edit().remove("handedness").commit();invokeMain(activity,"firstHandedness",none);capture("v016-first-hand.png");android.view.accessibility.AccessibilityNodeInfo first=test.getUiAutomation().getRootInActiveWindow();check(first!=null&&!first.findAccessibilityNodeInfosByText("右手 · 右下角").isEmpty(),"first-use handedness prompt");android.graphics.Rect handBounds=new android.graphics.Rect();first.findAccessibilityNodeInfosByText("右手 · 右下角").get(0).getBoundsInScreen(handBounds);long touch=android.os.SystemClock.uptimeMillis();test.sendPointerSync(android.view.MotionEvent.obtain(touch,touch,android.view.MotionEvent.ACTION_DOWN,handBounds.centerX(),handBounds.centerY(),0));test.sendPointerSync(android.view.MotionEvent.obtain(touch,touch+80,android.view.MotionEvent.ACTION_UP,handBounds.centerX(),handBounds.centerY(),0));test.waitForIdleSync();Thread.sleep(100);check("right".equals(activity.getSharedPreferences("settings",0).getString("handedness","")),"handedness preference saved");stop(activity);activity.getSharedPreferences("notification_seen",0).edit().clear().commit();Object store=field(activity,"academicStore");call(store,"clear",none);
        String table="<table><tr><th>课程名称</th><th>成绩</th></tr><tr><td>测试数学</td><td>88</td></tr></table>";
        JSONObject grades=fixture(activity,"grades",table);check(grades.optBoolean("complete")&&grades.getJSONArray("records").getJSONObject(0).getString("score").equals("88"),"grade table normalized");
        check(!fixture(activity,"grades",table+"<div class='pagination'>共2条</div>").optBoolean("complete"),"partial grade pages rejected");
        check(fixture(activity,"grades","<input type=password>"+table).optBoolean("login"),"login recognized");
        JSONObject exams=fixture(activity,"exams","<table><tr><th>课程名称</th><th>考试时间</th><th>考试地点</th></tr><tr><td>测试数学</td><td>2026-10-09 14:00-16:00</td><td>A201</td></tr></table>");check(exams.optBoolean("complete")&&exams.getJSONArray("records").getJSONObject(0).getString("startTime").equals("14:00"),"precise exam time extracted");
        check(!fixture(activity,"exams","<table><tr><th>课程名称</th><th>考试时间</th></tr><tr><td>未知考试</td><td>待定</td></tr></table>").optBoolean("complete"),"unknown exam time is not fabricated");
        JSONObject empty=fixture(activity,"grades","<script>window.__lutCapture={responses:[{url:'/jwapp/sys/test/modules/cjcx.do',data:{code:'0',datas:{cjcx:{extParams:{code:1},rows:[],totalSize:0}}}}]};</script>");check(empty.optBoolean("complete")&&empty.optBoolean("verifiedEmpty"),"verified empty result accepted");
        JSONObject catalog=fixture(activity,"catalog","<a href='/jwapp/sys/actualGrades/*default/index.do'>成绩查询</a><a href='https://example.test/no'>我的考试安排</a><a href='/jwapp/sys/a/index.do?ticket=secret'>课程查询</a>");check(catalog.getJSONArray("links").length()==1,"only observed safe official routes retained");
        Class<?>[] saveTypes={String.class,JSONObject.class,String.class,long.class};long now=System.currentTimeMillis();call(store,"save",saveTypes,"grades",grade("88",false),"test-account",now);check(((JSONArray)call(store,"pending",none)).length()==0,"first snapshot is baseline");
        call(store,"save",saveTypes,"grades",grade("88",true),"test-account",now+1);JSONArray pending=(JSONArray)call(store,"pending",none);check(pending.length()==1,"new grade queued once");call(store,"save",saveTypes,"grades",grade("88",true),"test-account",now+2);check(((JSONArray)call(store,"pending",none)).length()==1,"repeat update deduplicated");
        JSONObject malformed=grade("88",false);malformed.put("complete",false);boolean rejected=false;try{call(store,"save",saveTypes,"grades",malformed,"test-account",now+3);}catch(InvocationTargetException e){rejected=true;}check(rejected&&((JSONObject)call(store,"load",new Class<?>[]{String.class},"grades")).getJSONArray("records").length()==2,"failed update retains prior cache");
        call(store,"acknowledge",new Class<?>[]{JSONArray.class},pending);call(store,"save",saveTypes,"grades",grade("88",true),"test-account",now+3);check(((JSONArray)call(store,"pending",none)).length()==0,"acknowledged grade does not reappear");
        call(store,"save",saveTypes,"grades",grade("90",true),"test-account",now+4);check(((JSONArray)call(store,"pending",none)).length()==1,"changed published score queued");
        call(store,"save",saveTypes,"grades",grade("66",false),"different-account",now+5);check(((JSONArray)call(store,"pending",none)).length()==0,"account switch establishes clean baseline");
        call(store,"save",saveTypes,"grades",grade("66",true),"different-account",now+6);JSONArray beforeNotification=(JSONArray)call(store,"pending",none);NotificationManager manager=(NotificationManager)activity.getSystemService(Context.NOTIFICATION_SERVICE);check(manager.getActiveNotifications().length==0,"cache writes alone do not notify");
        invokeMain(activity,"loadAcademic",none);invokeMain(activity,"renderPage",new Class<?>[]{boolean.class},false);check(((View)field(activity,"gradeBanner")).getVisibility()==View.VISIBLE,"new grade top banner visible");
        Class<?> notify=Class.forName("cn.lut.schedule.GradeNotifications");shell("pm grant cn.lut.schedule android.permission.POST_NOTIFICATIONS");Thread.sleep(300);call(notify,"deliver",new Class<?>[]{Context.class,JSONArray.class},activity,beforeNotification);for(int wait=0;wait<30&&manager.getActiveNotifications().length==0;wait++)Thread.sleep(100);check(manager.getActiveNotifications().length==1,"foreground grade Android notification posted");long notificationTime=manager.getActiveNotifications()[0].getPostTime();call(notify,"deliver",new Class<?>[]{Context.class,JSONArray.class},activity,beforeNotification);Thread.sleep(300);check(manager.getActiveNotifications().length==1&&manager.getActiveNotifications()[0].getPostTime()==notificationTime,"notification not reposted on unchanged cache");capture("v016-grade-banner.png");manager.cancelAll();
        call(store,"save",saveTypes,"exams",exams,"different-account",now+7);invokeMain(activity,"loadAcademic",none);
        invokeMain(activity,"enableDemo",new Class<?>[]{boolean.class},true);stop(activity);check(((Integer)call(activity,"periodCount",none))==10,"demo exposes raw ten periods");check(((Integer)call(activity,"examBandHeight",none))>0,"exam appears inside weekly date column");
        activity.getSharedPreferences("settings",0).edit().putString("week_side","right").putString("course_colors","varied").commit();invokeMain(activity,"renderPage",new Class<?>[]{boolean.class},false);Thread.sleep(4000);capture("v016-home-light.png");
        activity.getSharedPreferences("settings",0).edit().putString("week_side","left").putString("course_colors","solid").putInt("solid_color",0xFFBAC6F0).commit();invokeMain(activity,"renderPage",new Class<?>[]{boolean.class},false);check(described((View)field(activity,"pages"),"周数切换 · 左下角")!=null,"left-handed week dock position");capture("v016-home-solid.png");
        android.graphics.Bitmap wallpaper=android.graphics.Bitmap.createBitmap(400,900,android.graphics.Bitmap.Config.ARGB_8888);android.graphics.Canvas canvas=new android.graphics.Canvas(wallpaper);android.graphics.Paint paint=new android.graphics.Paint();paint.setColor(android.graphics.Color.WHITE);canvas.drawRect(0,0,200,900,paint);paint.setColor(android.graphics.Color.BLACK);canvas.drawRect(200,0,400,900,paint);try(FileOutputStream file=new FileOutputStream(new File(activity.getFilesDir(),"background.jpg"))){wallpaper.compress(android.graphics.Bitmap.CompressFormat.JPEG,100,file);}wallpaper.recycle();activity.getSharedPreferences("settings",0).edit().putInt("veil",0).commit();invokeMain(activity,"loadBackground",none);invokeMain(activity,"renderPage",new Class<?>[]{boolean.class},false);test.waitForIdleSync();Thread.sleep(250);int rootWidth=((View)field(activity,"root")).getWidth(),rootHeight=((View)field(activity,"root")).getHeight();check(((Integer)call(activity,"sampleAt",new Class<?>[]{float.class,float.class},rootWidth*.2f,rootHeight*.1f))!=((Integer)call(activity,"sampleAt",new Class<?>[]{float.class,float.class},rootWidth*.8f,rootHeight*.9f)),"wallpaper sampled locally across full page");capture("v016-background-contrast.png");
        main(()->((ViewGroup)fieldUnchecked(activity,"nav")).getChildAt(2).performClick());check(text((View)field(activity,"pages"),"外观")!=null&&text((View)field(activity,"pages"),"同步与提醒")!=null&&text((View)field(activity,"pages"),"权限与手机系统")==null&&text((View)field(activity,"pages"),"错误报告")!=null,"functional settings groups");Thread.sleep(3800);capture("v016-settings-top.png");invokeMain(activity,"showErrorReport",none);test.waitForIdleSync();android.view.accessibility.AccessibilityNodeInfo dialog=test.getUiAutomation().getRootInActiveWindow();check(dialog!=null&&!dialog.findAccessibilityNodeInfosByText("LUTSCHEDULE_ERROR_REPORT_V1").isEmpty(),"standard error report subpage opens");capture("v018-report.png");test.getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);test.waitForIdleSync();
        Class<?> idle=Class.forName("cn.lut.schedule.IdleRefresh");call(idle,"operated",new Class<?>[]{Context.class},activity);JobScheduler scheduler=(JobScheduler)activity.getSystemService(Context.JOB_SCHEDULER_SERVICE);JobInfo job=scheduler.getPendingJob(2408);long last=activity.getSharedPreferences("settings",0).getLong("last_operation",0);check(job!=null&&job.isPersisted()&&job.getExtras().getLong("cycle")==last,"one persisted idle cycle scheduled");activity.getSharedPreferences("settings",0).edit().putLong("idle_consumed",last).commit();call(idle,"schedule",new Class<?>[]{Context.class},activity);check(scheduler.getPendingJob(2408)==null,"consumed idle cycle does not repeat");Thread.sleep(5);call(idle,"operated",new Class<?>[]{Context.class},activity);check(scheduler.getPendingJob(2408)!=null,"new operation rearms one-shot job");long idleCycle=System.currentTimeMillis()-48*3600000L;activity.getSharedPreferences("settings",0).edit().putLong("last_operation",idleCycle).commit();call(idle,"schedule",new Class<?>[]{Context.class},activity);String jobRun=shell("cmd jobscheduler run -f cn.lut.schedule 2408");for(int wait=0;wait<30&&activity.getSharedPreferences("settings",0).getLong("idle_consumed",0)!=idleCycle;wait++)Thread.sleep(100);check(activity.getSharedPreferences("settings",0).getLong("idle_consumed",0)==idleCycle,"actual JobService consumes eligible cycle: "+jobRun);Thread.sleep(400);check(manager.getActiveNotifications().length==0,"actual idle job is silent");call(idle,"operated",new Class<?>[]{Context.class},activity);
        new File(activity.getFilesDir(),"background.jpg").delete();activity.getSharedPreferences("settings",0).edit().putInt("veil",25).putString("course_colors","varied").putString("week_side","right").commit();invokeMain(activity,"loadBackground",none);call(store,"clear",none);invokeMain(activity,"loadAcademic",none);invokeMain(activity,"renderPage",new Class<?>[]{boolean.class},false);
        main(()->((ViewGroup)fieldUnchecked(activity,"nav")).getChildAt(1).performClick());View gradesService=described((View)field(activity,"pages"),"成绩查询");main(()->gradesService.performClick());check(field(activity,"loginWeb") instanceof WebView,"academic service opens official WebView");stop(activity);main(()->((ViewGroup)fieldUnchecked(activity,"nav")).getChildAt(0).performClick());invokeMain(activity,"renderPage",new Class<?>[]{boolean.class},false);
        Instrumentation.ActivityMonitor monitor=new Instrumentation.ActivityMonitor("cn.lut.schedule.MainActivity",null,false);test.addMonitor(monitor);main(()->{activity.getSharedPreferences("settings",0).edit().putString("theme","dark").commit();activity.recreate();});Activity dark=test.waitForMonitorWithTimeout(monitor,8000);test.removeMonitor(monitor);check(dark!=null,"dark theme recreation survives");stop(dark);check(Boolean.TRUE.equals(field(dark,"dark")),"dark appearance applied");capture("v016-home-dark.png");
        return "PASS: "+checks+" integration assertions: grade/exam DOM and observed JSON, validation, pagination, cache preservation, baseline/account isolation, durable inbox, foreground notification and dedup, top banner, ten raw periods, exams in date columns, settings/report, local full-page wallpaper contrast, left/right controls, official service WebView, one-shot persisted idle job and rearm, dark startup";
    }
    private Object fieldUnchecked(Object o,String name){try{return field(o,name);}catch(Exception e){throw new RuntimeException(e);}}
    private String shell(String command)throws Exception{android.os.ParcelFileDescriptor fd=test.getUiAutomation().executeShellCommand(command);try(java.io.InputStream in=new android.os.ParcelFileDescriptor.AutoCloseInputStream(fd)){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[1024];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);return out.toString("UTF-8");}}
}
