package cn.lut.schedule.tests;

import android.app.*;
import android.app.job.*;
import android.content.*;
import android.graphics.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.lang.reflect.*;
import java.time.*;
import java.util.*;

/** Synthetic imported files exercise real entry, storage and access rules. No fixture in the App. */
final class RuntimeSourceUi {
    final Instrumentation test;int checks;final Class<?>[] none={};
    RuntimeSourceUi(Instrumentation t){test=t;}
    void check(boolean yes,String reason){checks++;if(!yes)throw new AssertionError(reason);}
    static Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}
    static Object call(Object o,String n,Class<?>[] types,Object...args)throws Exception{Class<?> c=o instanceof Class?(Class<?>)o:o.getClass();Method m=c.getDeclaredMethod(n,types);m.setAccessible(true);return m.invoke(o instanceof Class?null:o,args);}
    void main(Runnable r){test.runOnMainSync(r);test.waitForIdleSync();}
    Object invoke(Object o,String n,Class<?>[] types,Object...args){Object[] result={null};main(()->{try{result[0]=call(o,n,types,args);}catch(Exception e){throw new RuntimeException(e);}});return result[0];}
    View text(View v,String label){if(v instanceof TextView&&label.equals(((TextView)v).getText().toString()))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View found=text(((ViewGroup)v).getChildAt(i),label);if(found!=null)return found;}return null;}
    View described(View v,String label){if(label.equals(String.valueOf(v.getContentDescription())))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View found=described(((ViewGroup)v).getChildAt(i),label);if(found!=null)return found;}return null;}
    void stop(Activity a)throws Exception{invoke(field(a,"coordinator"),"close",none);Object d=field(a,"loginDialog");if(d instanceof Dialog)main(()->((Dialog)d).dismiss());((Handler)field(a,"handler")).removeCallbacksAndMessages(null);invoke(Class.forName("cn.lut.schedule.Diagnostics"),"detach",new Class<?>[]{a.getClass()},a);}
    void navigate(Activity a,int page)throws Exception{invoke(a,"navigate",new Class<?>[]{int.class},page);Thread.sleep(300);test.waitForIdleSync();}
    void capture(String name)throws Exception{test.waitForIdleSync();Thread.sleep(250);Bitmap b=test.getUiAutomation().takeScreenshot();try(FileOutputStream o=new FileOutputStream(new File(test.getTargetContext().getExternalFilesDir(null),name))){b.compress(Bitmap.CompressFormat.PNG,100,o);}b.recycle();}
    static JSONObject fixture()throws Exception{
        JSONArray courses=new JSONArray(),weeks=new JSONArray();for(int i=1;i<=20;i++)weeks.put(i);
        String[] names={"高等数学","大学英语","程序设计","线性代数","大学物理","数据结构","体育","计算机实验","离散数学","人文选修课"};
        int[] days={1,2,4,3,5,4,2,3,1,6},starts={1,3,1,5,3,7,5,1,7,9};
        String[] rooms={"测试教学楼 A201","测试教学楼 B302","测试实验楼 C105","测试教学楼 A203","测试教学楼 D206","测试实验楼 C208","测试运动场","测试机房 B105","测试教学楼 A305","线上课堂"};
        for(int i=0;i<names.length;i++)courses.put(new JSONObject().put("name",names[i]).put("teacher","").put("room",rooms[i]).put("day",days[i]).put("start",starts[i]).put("end",starts[i]+1).put("weeks",weeks));
        return new JSONObject().put("schemaVersion",1).put("semester","合成验证课表 · 非学校真实数据").put("firstMonday",LocalDate.now(ZoneId.of("Asia/Shanghai")).with(DayOfWeek.MONDAY).minusWeeks(5).toString()).put("totalWeeks",20).put("periodCount",10).put("fetchedAt",System.currentTimeMillis()).put("courses",courses);
    }
    static void installFixture(Instrumentation t,Activity a,boolean official)throws Exception{
        JSONObject json=fixture();byte[] bytes=json.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);Throwable[] error={null};
        t.runOnMainSync(()->{try{call(a,"importSchedule",new Class<?>[]{byte[].class},bytes);if(official){Class<?> source=Class.forName("cn.lut.schedule.ScheduleCore$Source");Object value=Enum.valueOf((Class)source,"OFFICIAL"),snapshot=call(Class.forName("cn.lut.schedule.SnapshotStore"),"decode",new Class<?>[]{JSONObject.class,source},json,value);call(field(a,"store"),"save",new Class<?>[]{snapshot.getClass()},snapshot);a.getSharedPreferences("settings",0).edit().putString("entry_mode","official").commit();call(a,"loadSnapshot",new Class<?>[0]);call(a,"loadAcademic",new Class<?>[0]);call(a,"renderPage",new Class<?>[]{boolean.class},false);}}catch(Throwable e){error[0]=e;}});t.waitForIdleSync();if(error[0]!=null)throw new AssertionError(error[0]);
    }
    boolean uniform(View view,int color){if(view instanceof TextView&&((TextView)view).getCurrentTextColor()!=color)return false;if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++)if(!uniform(((ViewGroup)view).getChildAt(i),color))return false;return true;}
    void wallpaper(Activity a,int majority,boolean split)throws Exception{
        Bitmap b=Bitmap.createBitmap(split?1200:400,900,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(majority);Paint p=new Paint();if(split){p.setColor(0xFF142C48);c.drawRect(400,0,800,900,p);p.setColor(0xFFE8D8B2);c.drawRect(800,0,1200,900,p);}else{p.setColor(majority==Color.BLACK?Color.WHITE:Color.BLACK);c.drawRect(0,0,45,900,p);}
        try(FileOutputStream o=new FileOutputStream(new File(a.getFilesDir(),"background.jpg"))){b.compress(Bitmap.CompressFormat.JPEG,100,o);}b.recycle();a.getSharedPreferences("settings",0).edit().putString("background_layout",split?"split":"shared").putInt("veil",0).commit();invoke(a,"loadBackground",none);invoke(a,"renderPage",new Class<?>[]{boolean.class},false);Thread.sleep(250);
    }
    MotionEvent motion(long down,long at,int action,float cx,float cy,float span,int count){MotionEvent.PointerProperties[] props=new MotionEvent.PointerProperties[count];MotionEvent.PointerCoords[] coords=new MotionEvent.PointerCoords[count];for(int i=0;i<count;i++){props[i]=new MotionEvent.PointerProperties();props[i].id=i;props[i].toolType=MotionEvent.TOOL_TYPE_FINGER;coords[i]=new MotionEvent.PointerCoords();coords[i].x=cx+(i==0?-span:span);coords[i].y=cy;coords[i].pressure=1;coords[i].size=.2f;}return MotionEvent.obtain(down,at,action,count,props,coords,0,0,1,1,0,0,InputDevice.SOURCE_TOUCHSCREEN,0);}
    void pinch(View crop,RectF frame){main(()->{long down=SystemClock.uptimeMillis();float cx=frame.centerX(),cy=frame.centerY(),span=frame.width()*.22f;MotionEvent e=motion(down,down,MotionEvent.ACTION_DOWN,cx,cy,span,1);crop.dispatchTouchEvent(e);e.recycle();e=motion(down,down+20,MotionEvent.ACTION_POINTER_DOWN|(1<<MotionEvent.ACTION_POINTER_INDEX_SHIFT),cx,cy,span,2);crop.dispatchTouchEvent(e);e.recycle();for(int i=1;i<=5;i++){e=motion(down,down+20+i*20,MotionEvent.ACTION_MOVE,cx,cy,span*(1+i*.15f),2);crop.dispatchTouchEvent(e);e.recycle();}e=motion(down,down+150,MotionEvent.ACTION_POINTER_UP|(1<<MotionEvent.ACTION_POINTER_INDEX_SHIFT),cx,cy,span*1.75f,2);crop.dispatchTouchEvent(e);e.recycle();e=motion(down,down+170,MotionEvent.ACTION_UP,cx,cy,span*1.75f,1);crop.dispatchTouchEvent(e);e.recycle();});}
    String run(Activity a)throws Exception{
        stop(a);SharedPreferences prefs=a.getSharedPreferences("settings",0);View pages=(View)field(a,"pages");
        ViewGroup initialNav=(ViewGroup)field(a,"nav");check(initialNav.getChildAt(0).getContentDescription().equals("教务")&&initialNav.getChildAt(1).getContentDescription().equals("课表")&&initialNav.getChildAt(2).getContentDescription().equals("设置"),"default bottom order is academic/timetable/settings");
        check((Integer)field(a,"page")==0&&(Float)field(a,"backgroundPage")==1f,"startup remains timetable at center background position");
        check(text(pages,"登录 LUT 教务系统")!=null&&text(pages,"导入课表文件")!=null,"first launch offers both real data sources");
        check(field(a,"snapshot")==null&&field(a,"timetable")==null,"empty source draws no timetable or fabricated courses");
        check(field(a,"handDialog")==null&&field(a,"loginDialog")==null,"source choice is not covered by automatic dialogs");
        check(!prefs.contains("demo")&&!prefs.contains("developer"),"obsolete preferences removed during migration");
        check(Class.forName("cn.lut.schedule.ScheduleCore$Source").getEnumConstants().length==2,"only official and import sources remain");capture("source-ui-first-use.png");
        invoke(a,"showLogin",none);check(field(a,"loginDialog") instanceof Dialog,"login choice opens full screen official UI");check(prefs.getString("entry_mode","").equals("none"),"opening login does not grant a verified school session");stop(a);
        installFixture(test,a,false);Thread.sleep(220);Dialog hand=(Dialog)field(a,"handDialog");check(hand!=null&&hand.isShowing(),"hand choice follows first valid timetable");View handChoice=described(hand.getWindow().getDecorView(),"右手 · 右下角");main(handChoice::performClick);stop(a);
        check(prefs.getString("entry_mode","").equals("import"),"successful import persists source mode");check(field(a,"snapshot")!=null&&field(a,"timetable")!=null,"import renders native real file data");check(((Integer)call(a,"periodCount",none))==10,"import retains actual period count");
        Class<?> source=Class.forName("cn.lut.schedule.ScheduleCore$Source");JSONObject other=fixture().put("semester","旧官网缓存").put("fetchedAt",System.currentTimeMillis()-3600000);Object official=call(Class.forName("cn.lut.schedule.SnapshotStore"),"decode",new Class<?>[]{JSONObject.class,source},other,Enum.valueOf((Class)source,"OFFICIAL"));call(field(a,"store"),"save",new Class<?>[]{official.getClass()},official);invoke(a,"loadSnapshot",none);
        prefs.edit().remove("entry_mode").commit();call(Class.forName("cn.lut.schedule.AccessMode"),"migrate",new Class<?>[]{SharedPreferences.class,Class.forName("cn.lut.schedule.SnapshotStore")},prefs,field(a,"store"));check(prefs.getString("entry_mode","").equals("import"),"upgrade selects the latest valid source when both old caches exist");invoke(a,"loadSnapshot",none);
        check(!field(field(a,"snapshot"),"semester").equals("旧官网缓存"),"old official cache never overrides selected imported file");Object before=field(a,"snapshot");boolean[] rejected={false};main(()->{try{call(a,"importSchedule",new Class<?>[]{byte[].class},"{}".getBytes());}catch(Exception e){rejected[0]=true;}});check(rejected[0]&&field(a,"snapshot")==before&&prefs.getString("entry_mode","").equals("import"),"invalid import preserves old cache and selected source");
        long attempt=prefs.getLong("last_attempt",0);invoke(a,"refresh",none);check(attempt==prefs.getLong("last_attempt",0),"import mode never begins an official refresh");check(((JSONArray)field(a,"pendingChanges")).length()==0&&((JSONArray)field(a,"examRecords")).length()==0,"school grade and exam caches hidden in import mode");
        Class<?> idle=Class.forName("cn.lut.schedule.IdleRefresh");call(idle,"operated",new Class<?>[]{Context.class},a);check(((JobScheduler)a.getSystemService(Context.JOB_SCHEDULER_SERVICE)).getPendingJob(2408)==null,"import mode cancels all idle school jobs");
        Class<?> callback=Class.forName("cn.lut.schedule.SyncCoordinator$Callback");int[] calls={0};Object cb=Proxy.newProxyInstance(callback.getClassLoader(),new Class<?>[]{callback},(proxy,m,args)->{calls[0]++;return null;});Object coordinator=field(a,"coordinator");invoke(coordinator,"start",new Class<?>[]{callback},cb);check(calls[0]==1&&prefs.getLong("last_attempt",0)==attempt&&field(coordinator,"web")==null,"coordinator itself refuses network work in import mode");
        Field running=coordinator.getClass().getDeclaredField("finished"),listener=coordinator.getClass().getDeclaredField("callback");running.setAccessible(true);listener.setAccessible(true);main(()->{try{running.setBoolean(coordinator,false);listener.set(coordinator,cb);}catch(Exception e){throw new RuntimeException(e);}});int generation=(Integer)field(coordinator,"generation");Object allowed=invoke(coordinator,"authorized",new Class<?>[]{int.class},generation);check(Boolean.FALSE.equals(allowed)&&calls[0]==2&&prefs.getString("entry_mode","").equals("import")&&Boolean.TRUE.equals(field(coordinator,"finished")),"late background response cannot restore official mode after import");
        navigate(a,1);check(text((View)field(a,"pages"),"这些选项仅为 LUT 学生提供。登录 LUT 教务系统后可用。")!=null,"import academic restriction explained");Field groups=Class.forName("cn.lut.schedule.AcademicCatalog").getDeclaredField("GROUPS");groups.setAccessible(true);String[][] menu=(String[][])groups.get(null);Field categories=Class.forName("cn.lut.schedule.AcademicCatalog").getDeclaredField("CATEGORIES");categories.setAccessible(true);String[] names=(String[])categories.get(null);int blocked=0;
        for(int i=0;i<menu.length;i++){View cat=described((View)field(a,"pages"),"教务分类："+names[i]);main(cat::performClick);for(String label:menu[i]){View row=described((View)field(a,"pages"),label);check(row!=null&&!row.isEnabled(),"import disables service "+label);main(row::performClick);check(field(a,"loginWeb")==null&&(Integer)field(a,"page")==1,"disabled service cannot open a web window or switch timetable");blocked++;}}
        check(blocked==23,"all academic services restricted");prefs.edit().putInt("academic_category",0).commit();invoke(a,"renderPage",new Class<?>[]{boolean.class},false);capture("source-ui-import-academic.png");
        navigate(a,2);pages=(View)field(a,"pages");for(String removed:new String[]{"背景布局","官网小节","演示模式","官网连接详情"})check(text(pages,removed)==null,"obsolete setting removed: "+removed);
        check(text(pages,"底栏顺序")!=null,"tab order setting exists in operation group");
        for(String option:new String[]{"1,0,2","0,1,2","1,2,0","0,2,1","2,1,0","2,0,1"}){
            navigate(a,2);invoke(a,"applyTabOrder",new Class<?>[]{String.class},option);check((Integer)field(a,"page")==2&&prefs.getString("tab_order","").equals(option),"order save preserves current settings page and preference");
            ViewGroup reordered=(ViewGroup)field(a,"nav");String[] labels={"课表","教务","设置"};String[] order=option.split(",");
            check(reordered.getChildAt(0).getContentDescription().equals(labels[Integer.parseInt(order[0])])&&reordered.getChildAt(1).getContentDescription().equals(labels[Integer.parseInt(order[1])])&&reordered.getChildAt(2).getContentDescription().equals(labels[Integer.parseInt(order[2])]),"all six orders render the expected navigation");
            for(int slot=0;slot<3;slot++){int id=Integer.parseInt(order[slot]);View target=described((View)field(a,"nav"),labels[id]);main(target::performClick);Thread.sleep(320);check((Integer)field(a,"page")==id&&Math.abs((Float)field(a,"backgroundPage")-slot)<.01f,"navigation and panorama follow physical slot without changing page identity");}
        }
        navigate(a,2);Dialog orderDialog=(Dialog)invoke(a,"chooseTabOrder",none);View orderChoice=described(orderDialog.getWindow().getDecorView(),"教务 — 课表 — 设置");check(orderChoice!=null&&orderDialog.getClass().getName().equals("cn.lut.schedule.AppDialog"),"tab selection uses actual app styled dialog");capture("source-ui-tab-order.png");main(orderChoice::performClick);check(prefs.getString("tab_order","").equals("1,0,2")&&(Integer)field(a,"page")==2,"real dialog click saves default and keeps settings visible");
        check(text((View)field(a,"pages"),"Enota13")!=null,"developer attribution fixed");prefs.edit().putString("developer","someone else").commit();invoke(a,"renderPage",new Class<?>[]{boolean.class},false);check(text((View)field(a,"pages"),"Enota13")!=null&&text((View)field(a,"pages"),"someone else")==null,"old editable developer preference has no effect");prefs.edit().remove("developer").commit();
        View dev=(View)field(a,"developerRow");check(dev.getBackground()==null&&!dev.isSoundEffectsEnabled()&&!dev.isHapticFeedbackEnabled(),"developer row has no pressed visual sound or vibration");ClipboardManager clipboard=(ClipboardManager)a.getSystemService(Context.CLIPBOARD_SERVICE);main(()->clipboard.setPrimaryClip(ClipData.newPlainText("test","unchanged")));
        for(int i=0;i<4;i++)main(dev::performClick);check(field(a,"contactDialog")==null&&clipboard.getPrimaryClip().getItemAt(0).getText().equals("unchanged"),"one to four attribution taps do nothing visible");navigate(a,0);navigate(a,2);dev=(View)field(a,"developerRow");main(dev::performClick);check(field(a,"contactDialog")==null,"navigation interrupts consecutive tap sequence");for(int i=0;i<4;i++)main(dev::performClick);
        Dialog contact=(Dialog)field(a,"contactDialog");check(contact!=null&&text(contact.getWindow().getDecorView(),"你已经复制了开发者的邮箱，畅所欲言")!=null,"fifth tap shows the exact requested message");check(clipboard.getPrimaryClip().getItemAt(0).getText().equals("enota13official@gmail.com"),"fifth tap copies exact email without launching mail");check(contact.getClass().getName().equals("cn.lut.schedule.AppDialog"),"email popup uses app dialog");capture("source-ui-developer-contact.png");main(contact::dismiss);
        navigate(a,0);wallpaper(a,Color.WHITE,false);check((Integer)call(a,"screenForeground",none)==Color.BLACK,"light whole-screen majority chooses black");check(uniform((View)field(a,"root"),Color.BLACK),"all native labels have one foreground despite minority black patch");wallpaper(a,Color.BLACK,false);check((Integer)call(a,"screenForeground",none)==Color.WHITE&&uniform((View)field(a,"root"),Color.WHITE),"dark majority chooses white across the whole UI");
        View timetable=(View)field(a,"timetable"),firstTable=timetable;Bitmap rendered=Bitmap.createBitmap(timetable.getWidth(),timetable.getHeight(),Bitmap.Config.ARGB_8888);main(()->firstTable.draw(new Canvas(rendered)));float density=a.getResources().getDisplayMetrics().density;int gutter=Math.round(24*density),header=Math.round(64*density),width=rendered.getWidth(),empty=0;for(int d=0;d<7;d++){int x=Math.round(gutter+(width-gutter)*(d+.5f)/7);if(Color.alpha(rendered.getPixel(x,Math.round(53*density)))==0)empty++;}check(empty>=6,"date header has no connected backing strip");rendered.recycle();capture("source-ui-home-dominant.png");
        wallpaper(a,0xFFF0DFC3,true);int[] foreground=new int[3];for(int i=0;i<3;i++){navigate(a,i);foreground[i]=(Integer)call(a,"screenForeground",none);check(uniform((View)field(a,"root"),foreground[i]),"split background foreground uniform on page "+i);}check(foreground[0]==foreground[1]&&foreground[1]==foreground[2],"all three panorama pages retain one foreground across navigation");for(int id=0;id<3;id++){navigate(a,id);capture("source-ui-split-"+new String[]{"timetable","academic","settings"}[id]+".png");}
        prefs.edit().putInt("veil",100).commit();invoke(a,"renderPage",new Class<?>[]{boolean.class},false);check((Integer)call(a,"screenForeground",none)==Color.BLACK,"opacity participates in dominant foreground calculation");
        navigate(a,2);Dialog picker=(Dialog)invoke(a,"chooseSolidColor",none);View example=text(picker.getWindow().getDecorView(),"高等数学\n1–2节\nA201");check(example!=null,"palette preview places room on final line");View wheel=described(picker.getWindow().getDecorView(),"课程纯色色盘，可触摸选择颜色或输入十六进制颜色");int old=(Integer)field(wheel,"color");invoke(wheel,"onTouchEvent",new Class<?>[]{MotionEvent.class},MotionEvent.obtain(0,0,MotionEvent.ACTION_DOWN,wheel.getWidth()*.86f,wheel.getHeight()*.5f,0));check((Integer)field(wheel,"color")!=old,"color palette changes live");check(((TextView)example).getCurrentTextColor()==(Integer)call(a,"screenForeground",none),"palette preview shares screen text color");capture("source-ui-color.png");main(picker::dismiss);
        Bitmap image=Bitmap.createBitmap(1200,700,Bitmap.Config.ARGB_8888);new Canvas(image).drawColor(0xFF776050);ByteArrayOutputStream bytes=new ByteArrayOutputStream();image.compress(Bitmap.CompressFormat.PNG,100,bytes);image.recycle();File file=new File(a.getFilesDir(),"background.jpg");byte[] original=java.nio.file.Files.readAllBytes(file.toPath());invoke(a,"showBackgroundCrop",new Class<?>[]{byte[].class},bytes.toByteArray());Dialog cropDialog=(Dialog)field(a,"backgroundCrop");Object crop=field(cropDialog,"crop");Thread.sleep(300);RectF frame=(RectF)field(crop,"frame");pinch((View)crop,frame);check((Float)field(crop,"zoom")>1.2f,"actual two-finger gesture zooms crop");invoke(crop,"layoutMode",new Class<?>[]{boolean.class},true);View root=(View)field(a,"root");check(Math.abs(frame.width()/frame.height()-3*root.getWidth()/(float)root.getHeight())<.002,"three-part crop follows full-screen ratio");Bitmap exported=(Bitmap)call(crop,"export",none);check(Color.alpha(exported.getPixel(0,0))==255&&Color.alpha(exported.getPixel(exported.getWidth()-1,exported.getHeight()-1))==255,"crop leaves no empty image edges");exported.recycle();capture("source-ui-crop.png");main(cropDialog::dismiss);check(Arrays.equals(original,java.nio.file.Files.readAllBytes(file.toPath()))&&field(crop,"image")==null,"crop cancel preserves previous image and releases bitmap");
        prefs.edit().putString("handedness","right").putString("theme","light").putInt("veil",25).putString("background_layout","shared").commit();file.delete();invoke(a,"loadBackground",none);navigate(a,0);invoke(a,"renderPage",new Class<?>[]{boolean.class},false);Thread.sleep(10000);capture("source-ui-home-light.png");
        prefs.edit().putString("theme","dark").commit();invoke(a,"colors",none);invoke(a,"renderPage",new Class<?>[]{boolean.class},false);timetable=(View)field(a,"timetable");Bitmap darkCards=Bitmap.createBitmap(timetable.getWidth(),timetable.getHeight(),Bitmap.Config.ARGB_8888);View table=timetable;main(()->table.draw(new Canvas(darkCards)));List<RectF> rects=(List<RectF>)field(timetable,"hitRects");Set<Integer> hues=new HashSet<>();for(RectF rect:rects){int color=darkCards.getPixel(Math.round(rect.centerX()),Math.round(rect.bottom-2*density));float[] hsv=new float[3];Color.colorToHSV(color,hsv);if(hsv[1]>.1f)hues.add(Math.round(hsv[0]/20));}check(hues.size()>=3,"default dark courses contain several dark color hues");darkCards.recycle();check((Integer)call(a,"screenForeground",none)==Color.WHITE,"default dark native text stays uniformly white");capture("source-ui-home-dark.png");
        prefs.edit().putString("theme","light").commit();invoke(a,"colors",none);invoke(a,"renderPage",new Class<?>[]{boolean.class},false);navigate(a,2);capture("source-ui-settings.png");
        String report=(String)call(Class.forName("cn.lut.schedule.Diagnostics"),"report",new Class<?>[]{Context.class},a);check(report.contains("LUTSCHEDULE_ERROR_REPORT_V1")&&report.contains("v1.0.0")&&report.contains("https://github.com/Enota13-name/LUTschedule"),"diagnostic source links match shipped version");
        invoke(a,"logout",none);stop(a);navigate(a,0);check(field(a,"snapshot")==null&&field(a,"timetable")==null&&text((View)field(a,"pages"),"导入课表文件")!=null,"logout returns to real source choice without fake data");
        installFixture(test,a,true);stop(a);check(prefs.getString("entry_mode","").equals("official"),"verified official snapshot switches source mode");navigate(a,1);View grade=described((View)field(a,"pages"),"成绩查询");check(grade!=null&&grade.isEnabled(),"official mode restores school services");capture("source-ui-academic-official.png");navigate(a,0);
        return "PASS: "+checks+" source/UI assertions: source choice, no fabricated courses, import isolation and 23 blocked services, cache preservation, dominant unified foreground, header without strip, varied dark courses, palette room final line, native pinch crop, fixed attribution and five-tap clipboard, source report links";
    }
}
