package cn.lut.schedule.tests;
import android.app.*;
import android.content.*;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.lang.reflect.*;
import org.json.*;

/** Actual touch gestures, rendering and local diagnostics, using synthetic data only. */
final class RuntimeV018 {
    final Instrumentation test;int checks;final Class<?>[] none={};Activity fixtureActivity;
    RuntimeV018(Instrumentation t){test=t;}
    void check(boolean b,String label){checks++;if(!b)throw new AssertionError(label);}
    Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}
    Object call(Object o,String n,Class<?>[] types,Object...args)throws Exception{Class<?> c=o instanceof Class?(Class<?>)o:o.getClass();Method m=c.getDeclaredMethod(n,types);m.setAccessible(true);return m.invoke(o instanceof Class?null:o,args);}
    void main(Runnable r){test.runOnMainSync(r);test.waitForIdleSync();}
    Object invoke(Object o,String n,Class<?>[] types,Object...args){Object[] result={null};main(()->{try{result[0]=call(o,n,types,args);}catch(Exception e){throw new RuntimeException(e);}});return result[0];}
    View text(View v,String label){if(v instanceof TextView&&label.equals(((TextView)v).getText().toString()))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View found=text(((ViewGroup)v).getChildAt(i),label);if(found!=null)return found;}return null;}
    View described(View v,String label){if(label.equals(String.valueOf(v.getContentDescription())))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View found=described(((ViewGroup)v).getChildAt(i),label);if(found!=null)return found;}return null;}
    void capture(String file)throws Exception{Object official=field(fixtureActivity,"loginDialog");if(official instanceof Dialog&&((Dialog)official).isShowing())dismiss((Dialog)official);if(!file.equals("v018-error.png")){invoke(Class.forName("cn.lut.schedule.Diagnostics"),"detach",new Class<?>[]{fixtureActivity.getClass()},fixtureActivity);fixtureActivity.getSharedPreferences("diagnostics",0).edit().putBoolean("pending",false).commit();Object d=field(fixtureActivity,"errorDialog");if(d instanceof Dialog)dismiss((Dialog)d);}test.waitForIdleSync();Thread.sleep(350);Bitmap b=test.getUiAutomation().takeScreenshot();try(FileOutputStream out=new FileOutputStream(new File(test.getTargetContext().getExternalFilesDir(null),file))){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}
    void dismiss(Dialog d){main(d::dismiss);}
    void navigate(Activity a,int page)throws Exception{invoke(a,"navigate",new Class<?>[]{int.class},page);Thread.sleep(300);test.waitForIdleSync();}
    MotionEvent motion(long down,long at,int action,float cx,float cy,float span,int count){MotionEvent.PointerProperties[] props=new MotionEvent.PointerProperties[count];MotionEvent.PointerCoords[] coords=new MotionEvent.PointerCoords[count];for(int i=0;i<count;i++){props[i]=new MotionEvent.PointerProperties();props[i].id=i;props[i].toolType=MotionEvent.TOOL_TYPE_FINGER;coords[i]=new MotionEvent.PointerCoords();coords[i].x=cx+(i==0?-span:span);coords[i].y=cy;coords[i].pressure=1;coords[i].size=.2f;}return MotionEvent.obtain(down,at,action,count,props,coords,0,0,1,1,0,0,android.view.InputDevice.SOURCE_TOUCHSCREEN,0);}
    void pinch(View crop,RectF frame){main(()->{long down=android.os.SystemClock.uptimeMillis();float cx=frame.centerX(),cy=frame.centerY(),span=frame.width()*.22f;MotionEvent e=motion(down,down,MotionEvent.ACTION_DOWN,cx,cy,span,1);crop.dispatchTouchEvent(e);e.recycle();e=motion(down,down+20,MotionEvent.ACTION_POINTER_DOWN|(1<<MotionEvent.ACTION_POINTER_INDEX_SHIFT),cx,cy,span,2);crop.dispatchTouchEvent(e);e.recycle();for(int i=1;i<=5;i++){e=motion(down,down+20+i*20,MotionEvent.ACTION_MOVE,cx,cy,span*(1+i*.15f),2);crop.dispatchTouchEvent(e);e.recycle();}e=motion(down,down+150,MotionEvent.ACTION_POINTER_UP|(1<<MotionEvent.ACTION_POINTER_INDEX_SHIFT),cx,cy,span*1.75f,2);crop.dispatchTouchEvent(e);e.recycle();e=motion(down,down+170,MotionEvent.ACTION_UP,cx,cy,span*1.75f,1);crop.dispatchTouchEvent(e);e.recycle();});}
    String run(Activity a)throws Exception{fixtureActivity=a;((android.os.Handler)field(a,"handler")).removeCallbacksAndMessages(null);Object officialDialog=field(a,"loginDialog");if(officialDialog instanceof Dialog)dismiss((Dialog)officialDialog);
        Class<?> diagnostics=Class.forName("cn.lut.schedule.Diagnostics"),reports=Class.forName("cn.lut.schedule.ErrorReports");invoke(diagnostics,"detach",new Class<?>[]{a.getClass()},a);invoke(field(a,"coordinator"),"close",none);a.getSharedPreferences("diagnostics",0).edit().clear().commit();
        android.content.SharedPreferences settings=a.getSharedPreferences("settings",0);invoke(field(a,"academicStore"),"clear",none);invoke(a,"loadAcademic",none);settings.edit().putString("background_layout","shared").putInt("veil",0).putString("course_colors","varied").commit();invoke(a,"enableDemo",new Class<?>[]{boolean.class},true);
        View root=(View)field(a,"root");float ratio=root.getWidth()/(float)root.getHeight();Bitmap source=Bitmap.createBitmap(1800,Math.round(1800/(3*ratio)),Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(source);Paint paint=new Paint(3);int[] palette={0xFFD6C2AC,0xFFA1AFB8,0xFF999987};for(int i=0;i<3;i++){paint.setShader(new LinearGradient(0,0,0,source.getHeight(),palette[i],palette[i]-0x00303030,Shader.TileMode.CLAMP));canvas.drawRect(i*600,0,(i+1)*600,source.getHeight(),paint);}paint.setShader(null);paint.setColor(0x55999999);canvas.drawCircle(300,source.getHeight()*.68f,310,paint);canvas.drawCircle(900,source.getHeight()*.78f,310,paint);canvas.drawCircle(1500,source.getHeight()*.6f,310,paint);ByteArrayOutputStream encoded=new ByteArrayOutputStream();source.compress(Bitmap.CompressFormat.PNG,100,encoded);source.recycle();byte[] bytes=encoded.toByteArray();
        File file=new File(a.getFilesDir(),"background.jpg");byte[] old=file.exists()?java.nio.file.Files.readAllBytes(file.toPath()):null;
        invoke(a,"showBackgroundCrop",new Class<?>[]{byte[].class},bytes);Thread.sleep(350);test.waitForIdleSync();Dialog cropDialog=(Dialog)field(a,"backgroundCrop");Object crop=field(cropDialog,"crop");RectF frame=(RectF)field(crop,"frame");check(frame.width()>0,"crop laid out before gestures");pinch((View)crop,frame);check(((Float)field(crop,"zoom"))>1.2f,"real two-finger gesture zooms image: "+field(crop,"zoom")+" frame="+frame);invoke(crop,"zoomTo",new Class<?>[]{float.class,float.class,float.class},99f,frame.centerX(),frame.centerY());check(((Float)field(crop,"zoom"))==4f,"pinch zoom is bounded to protect bitmap size");invoke(crop,"layoutMode",new Class<?>[]{boolean.class},true);check(Math.abs(frame.width()/frame.height()-ratio*3)<.002,"three-part crop preserves page ratio");check(settings.getString("background_layout","").equals("shared"),"crop mode not persisted before confirmation");Bitmap exported=(Bitmap)call(crop,"export",none);check(Math.abs(exported.getWidth()/(float)exported.getHeight()-ratio*3)<.002,"panorama export ratio matches all three pages");check(Color.alpha(exported.getPixel(0,0))==255&&Color.alpha(exported.getPixel(exported.getWidth()-1,exported.getHeight()-1))==255,"panorama contains no blank edges");exported.recycle();View cropView=(View)crop;main(cropView::invalidate);capture("v018-crop.png");dismiss(cropDialog);check(old==null?!file.exists():java.util.Arrays.equals(old,java.nio.file.Files.readAllBytes(file.toPath())),"cancel preserves image bytes");check(field(crop,"image")==null,"cancel releases decoded photo");
        invoke(a,"showBackgroundCrop",new Class<?>[]{byte[].class},bytes);cropDialog=(Dialog)field(a,"backgroundCrop");crop=field(cropDialog,"crop");invoke(crop,"layoutMode",new Class<?>[]{boolean.class},true);View confirm=text(cropDialog.getWindow().getDecorView(),"使用");main(confirm::performClick);check(settings.getString("background_layout","").equals("split")&&file.exists(),"confirm persists mode and picture together");android.media.ExifInterface exif=new android.media.ExifInterface(file.getPath());check("LUTBACKGROUND:split".equals(exif.getAttribute(android.media.ExifInterface.TAG_USER_COMMENT)),"saved photo contains recoverable layout metadata");settings.edit().putString("background_layout","shared").commit();invoke(a,"loadBackground",none);check(settings.getString("background_layout","").equals("split"),"photo repairs mismatched layout preference");
        Thread.sleep(2700);int[] samples=new int[3];for(int page=0;page<3;page++){navigate(a,page);samples[page]=(Integer)call(a,"sampleAt",new Class<?>[]{float.class,float.class},root.getWidth()*.5f,root.getHeight()*.5f);check(Math.abs((Float)field(a,"backgroundPage")-page)<.001,"background transition reaches page "+page);capture(new String[]{"v018-home-wallpaper.png","v018-academic.png","v018-settings.png"}[page]);}navigate(a,1);View category=described((View)field(a,"pages"),"教务分类：学籍管理");main(category::performClick);Thread.sleep(350);TextView changed=(TextView)text((View)field(a,"pages"),"转专业管理");check(changed!=null&&(changed.getCurrentTextColor()==Color.BLACK||changed.getCurrentTextColor()==Color.WHITE),"dynamic academic category adapts text to wallpaper");View restoreCategory=described((View)field(a,"pages"),"教务分类：师生服务");main(restoreCategory::performClick);navigate(a,2);check(samples[0]!=samples[1]&&samples[1]!=samples[2]&&samples[0]!=samples[2],"each tab displays its own panorama section");
        View pages=(View)field(a,"pages");check(text(pages,"背景透明度")!=null&&text(pages,"权限与手机系统")==null&&text(pages,"屏幕遮盖")==null,"settings rename and obsolete branch removal");check(text(pages,"复制错误报告")!=null,"report available at bottom of settings");settings.edit().putString("background_layout","shared").commit();int same=0;for(int page=0;page<3;page++){navigate(a,page);int value=(Integer)call(a,"sampleAt",new Class<?>[]{float.class,float.class},root.getWidth()*.5f,root.getHeight()*.5f);if(page==0)same=value;check(value==same,"shared wallpaper applies to tab "+page);}
        Dialog color=(Dialog)invoke(a,"chooseSolidColor",none);check(color.getClass().getName().equals("cn.lut.schedule.AppDialog")&&!(color instanceof AlertDialog),"course picker uses app-owned dialog");View example=text(color.getWindow().getDecorView(),"高等数学\nA201\n1–2节");check(example!=null,"course example appears beside palette");View wheel=described(color.getWindow().getDecorView(),"课程纯色色盘，可触摸选择颜色或输入十六进制颜色");int before=(Integer)field(wheel,"color");invoke(wheel,"onTouchEvent",new Class<?>[]{MotionEvent.class},MotionEvent.obtain(0,0,MotionEvent.ACTION_DOWN,wheel.getWidth()*.86f,wheel.getHeight()*.5f,0));check(before!=(Integer)field(wheel,"color"),"palette touch changes selected color");Bitmap tile=Bitmap.createBitmap(20,20,Bitmap.Config.ARGB_8888);Canvas tileCanvas=new Canvas(tile);Rect tileBounds=new Rect(example.getBackground().getBounds());example.getBackground().setBounds(0,0,20,20);example.getBackground().draw(tileCanvas);example.getBackground().setBounds(tileBounds);check(tile.getPixel(10,10)==(Integer)field(wheel,"color"),"live course example follows palette");tile.recycle();capture("v018-color.png");dismiss(color);check(settings.getString("course_colors","").equals("varied"),"cancel does not change course preference");
        navigate(a,0);Object timetable=field(a,"timetable");int[] origin=new int[2],position=new int[2];root.getLocationInWindow(origin);((View)timetable).getLocationInWindow(position);float density=a.getResources().getDisplayMetrics().density;int headerColor=(Integer)call(timetable,"headerColor",new Class<?>[]{float.class,float.class,float.class,float.class},(float)(position[0]-origin[0]),(float)(position[1]-origin[1]),24*density,(((View)timetable).getWidth()-24*density)/7);check(headerColor==Color.BLACK||headerColor==Color.WHITE,"one contrast color chosen for complete date row");check(((View)timetable).getContentDescription().toString().contains("官网实际小节"),"raw period count remains documented to screen reader");
        a.getSharedPreferences("diagnostics",0).edit().clear().commit();for(int i=0;i<30;i++)call(reports,"breadcrumb",new Class<?>[]{Context.class,String.class},a,"测试步骤 "+i);check(new JSONArray(a.getSharedPreferences("diagnostics",0).getString("steps","[]")).length()==24,"breadcrumbs bounded to 24");for(int i=0;i<15;i++)call(reports,"record",new Class<?>[]{Context.class,String.class,String.class,Throwable.class,boolean.class},a,"合成错误 "+i,"token=SECRET",new IllegalStateException("{\"password\":\"PRIVATE SECRET\"}"),false);check(new JSONArray(a.getSharedPreferences("diagnostics",0).getString("events","[]")).length()==12,"error history bounded to 12 events");String id=(String)call(reports,"record",new Class<?>[]{Context.class,String.class,String.class,Throwable.class,boolean.class},a,"合成错误 14","token=SECRET",new IllegalStateException("{\"password\":\"PRIVATE SECRET\"}"),false);JSONArray events=new JSONArray(a.getSharedPreferences("diagnostics",0).getString("events","[]"));check(events.getJSONObject(events.length()-1).getInt("count")==2,"repeated error coalesces without extra events");String report=(String)call(reports,"export",new Class<?>[]{Context.class},a);check(report.startsWith("LUTSCHEDULE_ERROR_REPORT_V1")&&report.contains("https://github.com/Enota13-name/LUTschedule")&&report.contains("release/0.1.8-preview"),"report schema and exact source links");check(report.contains("Android:")&&report.contains("WebView:")&&report.contains("RuntimeV018.java"),"report includes environment and stack location");check(!report.contains("SECRET")&&!report.contains("PRIVATE"),"report redacts exception secrets");check(report.contains("[交给 AI 的任务]")&&report.contains("[用户可补充]"),"report includes concrete repair guidance and reproduction fields");
        invoke(a,"showDiagnosticError",new Class<?>[]{String.class},id);Dialog error=(Dialog)field(a,"errorDialog");check(error.getClass().getName().equals("cn.lut.schedule.AppDialog")&&text(error.getWindow().getDecorView(),"去设置")!=null,"nonfatal error has custom report guidance popup");capture("v018-error.png");View go=text(error.getWindow().getDecorView(),"去设置");main(go::performClick);Thread.sleep(400);check(((Integer)field(a,"page"))==2,"error action goes to settings");ScrollView scroll=(ScrollView)field(a,"settingsScroll");check(scroll.getScrollY()>0,"error action scrolls to report at bottom");invoke(diagnostics,"copy",new Class<?>[]{Activity.class},a);ClipboardManager clipboard=(ClipboardManager)a.getSystemService(Context.CLIPBOARD_SERVICE);check(clipboard.getPrimaryClip()!=null&&clipboard.getPrimaryClip().getItemAt(0).getText().toString().startsWith("LUTSCHEDULE_ERROR_REPORT_V1"),"complete structured report copied");
        call(reports,"record",new Class<?>[]{Context.class,String.class,String.class,Throwable.class,boolean.class},a,"合成启动错误","fixture",new IllegalStateException("fixture"),true);check((Boolean)call(diagnostics,"needsRecovery",new Class<?>[]{Context.class},a),"fatal marker persists for next launch");call(diagnostics,"clearFatal",new Class<?>[]{Context.class},a);check(!(Boolean)call(diagnostics,"needsRecovery",new Class<?>[]{Context.class},a),"recovery retry clears marker");a.getSharedPreferences("diagnostics",0).edit().clear().commit();settings.edit().putString("background_layout","shared").commit();file.delete();invoke(a,"loadBackground",none);navigate(a,0);invoke(a,"renderPage",new Class<?>[]{boolean.class},false);
        return "PASS: "+checks+" v018 assertions: actual pinch gesture, panorama crop/export/atomic save/cancel, shared and split backgrounds on three tabs, transitions, custom palette live example, uniform date foreground, flat settings, bounded and redacted error reports, source links, popup/navigation/clipboard and fatal recovery markers";
    }
}
