package cn.lut.schedule.tests;
import android.app.*;
import android.content.*;
import android.graphics.*;
import android.view.*;
import android.webkit.*;
import org.json.*;
import java.io.*;
import java.lang.reflect.*;
import java.util.concurrent.*;

/** App integration with synthetic records and public school protocol structure; no school session. */
final class RuntimeV017 {
    final Instrumentation test;int checks;
    RuntimeV017(Instrumentation t){test=t;}
    void check(boolean value,String reason){checks++;if(!value)throw new AssertionError(reason);}
    Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}
    Object call(Object o,String n,Class<?>[] types,Object...args)throws Exception{Method m=(o instanceof Class?(Class<?>)o:o.getClass()).getDeclaredMethod(n,types);m.setAccessible(true);return m.invoke(o instanceof Class?null:o,args);}
    void main(Runnable r){test.runOnMainSync(r);test.waitForIdleSync();}
    void invoke(Object o,String n,Class<?>[] types,Object...args){main(()->{try{call(o,n,types,args);}catch(Exception e){throw new RuntimeException(e);}});}
    View text(View v,String n){if(v instanceof android.widget.TextView&&n.equals(((android.widget.TextView)v).getText().toString()))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View x=text(((ViewGroup)v).getChildAt(i),n);if(x!=null)return x;}return null;}
    void capture(String n)throws Exception{Thread.sleep(300);Bitmap b=test.getUiAutomation().takeScreenshot();try(FileOutputStream o=new FileOutputStream(new File(test.getTargetContext().getExternalFilesDir(null),n))){b.compress(Bitmap.CompressFormat.PNG,100,o);}b.recycle();}
    JSONObject fixture(Activity a,String kind,String html,String url,boolean course)throws Exception{
        Class<?> reader=Class.forName(course?"cn.lut.schedule.CourseReader":"cn.lut.schedule.AcademicReader"),cb=Class.forName(course?"cn.lut.schedule.CourseReader$Callback":"cn.lut.schedule.AcademicReader$Callback");JSONObject[] data={null};Throwable[] error={null};CountDownLatch latch=new CountDownLatch(1);WebView[] view={null};
        Object callback=Proxy.newProxyInstance(cb.getClassLoader(),new Class<?>[]{cb},(p,m,args)->{data[0]=(JSONObject)args[0];error[0]=(Throwable)args[1];latch.countDown();return null;});
        main(()->{view[0]=new WebView(a);view[0].getSettings().setJavaScriptEnabled(true);((ViewGroup)a.getWindow().getDecorView()).addView(view[0],new ViewGroup.LayoutParams(1,1));view[0].setWebViewClient(new WebViewClient(){boolean once;public void onPageFinished(WebView v,String u){if(once)return;once=true;try{if(course)call(reader,"read",new Class<?>[]{WebView.class,cb},v,callback);else call(reader,"read",new Class<?>[]{WebView.class,String.class,cb},v,kind,callback);}catch(Exception e){error[0]=e;latch.countDown();}}});view[0].loadDataWithBaseURL(url,html,"text/html","UTF-8",null);});
        if(!latch.await(30,TimeUnit.SECONDS))throw new AssertionError("reader timeout: "+kind);main(()->{((ViewGroup)view[0].getParent()).removeView(view[0]);view[0].destroy();});if(error[0]!=null)throw new AssertionError(error[0]);return data[0];
    }
    String run(Activity a)throws Exception{
        Class<?>[] none={};invoke(Class.forName("cn.lut.schedule.Diagnostics"),"detach",new Class<?>[]{a.getClass()},a);invoke(field(a,"coordinator"),"close",none);Object open=field(a,"loginDialog");if(open!=null)main(()->((Dialog)open).dismiss());invoke(field(a,"coordinator"),"close",none);
        Class<?> catalog=Class.forName("cn.lut.schedule.AcademicCatalog");Field groups=catalog.getDeclaredField("GROUPS");groups.setAccessible(true);String[][] menu=(String[][])groups.get(null);int count=0;for(String[] group:menu)for(String name:group){String route=(String)call(catalog,"route",new Class<?>[]{android.content.SharedPreferences.class,String.class},a.getSharedPreferences("settings",0),name);check(route.startsWith("https://jwxt.lut.edu.cn/jwapp/sys/")&&!route.equals("https://jwxt.lut.edu.cn/"),"direct entry "+name);count++;}check(count==23&&menu[1].length==3&&menu[2].length==2&&menu[3].length==4,"all four verified categories");
        JSONObject portal=fixture(a,"catalog","<div class=p_title>师生服务</div><div class=p_card><div class=p_card_name>成绩查询</div><div data-url='/jwapp/sys/emaphome/appShow.do?id=33289050114342f8953198fffdf6231a'>进入应用</div></div>","https://jwxt.lut.edu.cn/jwapp/sys/emaphome/portal/index.do",false);check(portal.optBoolean("portal")&&portal.optBoolean("authenticated")&&portal.getJSONArray("links").toString().contains("成绩查询"),"hidden card URL associated with actual service title");
        String gradeScript="window.fetch=function(url,opt){var p=new URLSearchParams(opt.body),page=Number(p.get('pageNumber'));if(!url.endsWith('/xscjcx.do')||!p.get('querySetting').includes('SFYX'))throw Error('wrong grade query');var rows=page===1?[{WID:'G1',KCM:'测试数学',ZCJ:'88',XNXQDM:'T1'}]:[{WID:'G2',KCM:'测试英语',ZCJ:'75',XSZCJMC:'中等',XNXQDM:'T1'}];return Promise.resolve(new Response(JSON.stringify({code:'0',datas:{xscjcx:{extParams:{code:1},totalSize:2,pageSize:1,rows:rows}}})));};";
        JSONObject grades=fixture(a,"grades","<html><body><script>"+gradeScript+"</script></body></html>","https://jwxt.lut.edu.cn/jwapp/sys/cjcx/*default/index.do?EMAP_LANG=zh#/cjcx",false);check(grades.optBoolean("complete")&&grades.getJSONArray("records").length()==2,"all grade pages fetched automatically");check(grades.getJSONArray("records").getJSONObject(1).getString("score").equals("中等"),"published grade display label retained");
        String jq="window.jQuery={ajax:function(o){var done,fail;window.fetch(o.url,{method:o.type,body:new URLSearchParams(o.data).toString()}).then(function(r){return r.json();}).then(function(v){done(v);}).catch(function(e){if(fail)fail({status:500},'error');});var result={done:function(f){done=f;return result;},fail:function(f){fail=f;return result;}};return result;}};";
        check(fixture(a,"grades","<html><body><script>"+gradeScript+jq+"</script></body></html>","https://jwxt.lut.edu.cn/jwapp/sys/cjcx/*default/index.do?EMAP_LANG=zh#/cjcx",false).optBoolean("complete"),"website AJAX transport supported");
        check(!fixture(a,"grades","<html><body><script>window.fetch=function(){return Promise.resolve(new Response('{}',{status:503}));};</script></body></html>","https://jwxt.lut.edu.cn/jwapp/sys/cjcx/*default/index.do?EMAP_LANG=zh#/cjcx",false).optBoolean("complete"),"failed official query cannot mark empty success");
        String examScript="window.fetch=function(url,opt){var data;if(url.endsWith('/dqxnxq.do'))data={code:'0',datas:{dqxnxq:{extParams:{code:1},rows:[{DM:'2026-2027-1'}]}}};else{var p=JSON.parse(new URLSearchParams(opt.body).get('requestParamStr'));if(p.XNXQDM!=='2026-2027-1')throw Error('wrong term');data={code:'0',datas:{cxxsksap:{extParams:{code:1},rows:[{WID:'E1',KCM:'测试数学',KSRQ:'2026-10-09',KSSJMS:'2026-10-09 13:30-15:30(星期五)',JASMC:'A201',KSRWZT:'1',SFXYAPKS:'1',SFAPSJ:'1'},{WID:'E2',KCM:'时间待定',KSRWZT:'1',SFXYAPKS:'0',SFAPSJ:'0'},{WID:'E3',KCM:'未发布',KSRWZT:'0',SFFBSJ:'0'}]}}};}return Promise.resolve(new Response(JSON.stringify(data)));};";
        JSONObject exams=fixture(a,"exams","<html><body><script>"+examScript+"</script></body></html>","https://jwxt.lut.edu.cn/jwapp/sys/studentWdksapApp/*default/index.do?EMAP_LANG=zh#/wdksap",false);check(exams.optBoolean("complete")&&exams.getJSONArray("records").length()==1,"only published timed exam event rendered");check(exams.getJSONArray("records").getJSONObject(0).getString("startTime").equals("13:30")&&exams.getJSONArray("records").getJSONObject(0).getString("endTime").equals("15:30"),"real KSSJMS range parsed");check(exams.getJSONArray("unscheduledRecords").length()==1,"published untimed exam kept separately");
        String courseScript="window.fetch=function(url,opt){var q=new URLSearchParams(opt.body),action=url.split('/').pop().replace('.do',''),rows,total;switch(action){case 'dqxnxq':rows=[{DM:'2026-2027-1',MC:'测试学期'}];break;case 'cxxszhxqkb':if(q.get('SKZC'))throw Error('week filter must be omitted');rows=[{KCM:'完整课表数学',SKXQ:1,KSJC:1,JSJC:2,ZCMC:'1-16周',XNXQDM:'2026-2027-1'}];total=1;break;case 'cxxljc':rows=[{ZZC:20}];break;case 'dqzc':var d=new Date(q.get('RQ')+'T00:00:00Z');rows=[{ZC:6,XQJ:d.getUTCDay()||7}];break;default:throw Error('unexpected or mutating endpoint');}var b={extParams:{code:1},rows:rows};if(total!=null)b.totalSize=total;var data={code:'0',datas:{}};data.datas[action]=b;return Promise.resolve(new Response(JSON.stringify(data)));};";
        JSONObject course=fixture(a,"", "<html><body><td data-unit=10></td><script>"+courseScript+"</script></body></html>","https://jwxt.lut.edu.cn/jwapp/sys/wdkb/*default/index.do?EMAP_LANG=zh#/xskcb",true);check(course.optBoolean("complete")&&course.optInt("totalWeeks")==20&&!course.optString("firstMonday").isEmpty(),"current real query path and automatic first teaching Monday");check(java.time.LocalDate.parse(course.getString("firstMonday")).getDayOfWeek()==java.time.DayOfWeek.MONDAY,"calendar-derived date is Monday");
        invoke(a,"showOfficial",new Class<?>[]{String.class,String.class},"成绩查询","https://jwxt.lut.edu.cn/jwapp/sys/emaphome/appShow.do?id=33289050114342f8953198fffdf6231a");Dialog dialog=(Dialog)field(a,"loginDialog");WebView web=(WebView)field(a,"loginWeb");test.waitForIdleSync();check(dialog.getWindow().getAttributes().width==-1&&dialog.getWindow().getAttributes().height==-1,"official dialog uses full screen window");check(web.getWidth()==dialog.getWindow().getDecorView().getWidth()&&web.getHeight()>dialog.getWindow().getDecorView().getHeight()*.7,"WebView fills width and most screen");check(text(dialog.getWindow().getDecorView(),"读取当前页面")==null,"no routine manual read button");
        main(()->web.loadDataWithBaseURL("https://jwxt.lut.edu.cn/jwapp/sys/cjcx/*default/index.do?EMAP_LANG=zh#/cjcx","<html><meta name='viewport' content='width=device-width'><body style='font-family:sans-serif'><h2>成绩查询 · 测试页面</h2><p>全屏官网视图布局验证</p></body></html>","text/html","UTF-8",null));Thread.sleep(800);capture("v017-fullscreen-web.png");main(dialog::dismiss);invoke(field(a,"coordinator"),"close",none);
        invoke(a,"showOfficial",new Class<?>[]{String.class,String.class},"官网登录","https://jwxt.lut.edu.cn/");WebView login=(WebView)field(a,"loginWeb");CountDownLatch routed=new CountDownLatch(1);main(()->{login.stopLoading();try{Field f=a.getClass().getDeclaredField("loginPageFailed");f.setAccessible(true);f.setBoolean(a,false);}catch(Exception e){throw new RuntimeException(e);}login.setWebViewClient(new WebViewClient(){public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest request){if(request.getUrl().getPath()!=null&&request.getUrl().getPath().contains("/sys/wdkb/")){routed.countDown();return new WebResourceResponse("text/html","UTF-8",new ByteArrayInputStream("<html><body>自动课表路由测试</body></html>".getBytes(java.nio.charset.StandardCharsets.UTF_8)));}return null;}public void onPageStarted(WebView v,String u,Bitmap b){if(u.contains("/sys/wdkb/"))routed.countDown();}public void onPageFinished(WebView v,String u){if(u.contains("emaphome/portal"))try{call(a,"readAcademicFromLogin",none);}catch(Exception e){throw new RuntimeException(e);}}});login.loadDataWithBaseURL("https://jwxt.lut.edu.cn/jwapp/sys/emaphome/portal/index.do","<div class=p_title>师生服务</div><div class=p_card_name>我的课表</div>","text/html","UTF-8",null);});boolean autoRouted=routed.await(8,TimeUnit.SECONDS);String[] routeUrl={""};main(()->routeUrl[0]=login.getUrl());check(autoRouted||routeUrl[0].contains("/sys/wdkb/"),"login portal automatically routes to exact timetable page: "+routeUrl[0]+" / "+field(a,"officialService")+" / "+field(a,"loginSyncQueued")+" / failed="+field(a,"loginPageFailed"));Dialog loginDialog=(Dialog)field(a,"loginDialog");main(loginDialog::dismiss);invoke(field(a,"coordinator"),"close",none);
        invoke(a,"enableDemo",new Class<?>[]{boolean.class},true);invoke(field(a,"coordinator"),"close",none);a.getSharedPreferences("settings",0).edit().putInt("veil",15).commit();
        Bitmap source=Bitmap.createBitmap(1200,800,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(source);Paint p=new Paint();p.setColor(0xFFCFAD86);canvas.drawRect(0,0,1200,800,p);p.setColor(0xFF44604C);canvas.drawCircle(920,360,280,p);p.setColor(0xFFE9D4AB);canvas.drawCircle(360,280,180,p);ByteArrayOutputStream bytes=new ByteArrayOutputStream();source.compress(Bitmap.CompressFormat.PNG,100,bytes);source.recycle();File background=new File(a.getFilesDir(),"background.jpg");byte[] prior=background.exists()?java.nio.file.Files.readAllBytes(background.toPath()):null;
        invoke(a,"showBackgroundCrop",new Class<?>[]{byte[].class},bytes.toByteArray());Dialog cropDialog=(Dialog)field(a,"backgroundCrop");Object crop=field(cropDialog,"crop");RectF frame=(RectF)field(crop,"frame");View root=(View)field(a,"root");check(Math.abs(frame.width()/frame.height()-root.getWidth()/(float)root.getHeight())<.001,"crop follows entire home aspect ratio");invoke(crop,"zoomTo",new Class<?>[]{float.class,float.class,float.class},2f,frame.centerX(),frame.centerY());invoke(crop,"clamp",none);main(()->{try{field(crop,"preview");Field f=crop.getClass().getDeclaredField("preview");f.setAccessible(true);f.setBoolean(crop,true);((View)crop).invalidate();}catch(Exception e){throw new RuntimeException(e);}});Thread.sleep(6000);capture("v017-crop-preview.png");Bitmap cropped=(Bitmap)call(crop,"export",none);check(Math.abs(cropped.getWidth()/(float)cropped.getHeight()-root.getWidth()/(float)root.getHeight())<.001,"export preserves preview ratio");check(Color.alpha(cropped.getPixel(0,0))==255&&Color.alpha(cropped.getPixel(cropped.getWidth()-1,cropped.getHeight()-1))==255,"crop corners contain image with no empty edges");cropped.recycle();main(cropDialog::dismiss);check(prior==null?!background.exists():java.util.Arrays.equals(prior,java.nio.file.Files.readAllBytes(background.toPath())),"cancel preserves exact old wallpaper");check(field(crop,"image")==null,"cancel releases bitmap");
        boolean priorDark=(Boolean)field(a,"dark");String priorTheme=a.getSharedPreferences("settings",0).getString("theme","light");a.getSharedPreferences("settings",0).edit().putString("theme","system").commit();Field darkField=a.getClass().getDeclaredField("dark");darkField.setAccessible(true);main(()->{try{darkField.setBoolean(a,true);}catch(Exception e){throw new RuntimeException(e);}});invoke(a,"showBackgroundCrop",new Class<?>[]{byte[].class},bytes.toByteArray());Dialog darkCrop=(Dialog)field(a,"backgroundCrop");check(((android.widget.TextView)text(darkCrop.getWindow().getDecorView(),"使用")).getCurrentTextColor()==Color.WHITE&&((android.widget.TextView)text(darkCrop.getWindow().getDecorView(),"取消")).getCurrentTextColor()==Color.WHITE,"crop actions remain readable when resolved system theme is dark");main(darkCrop::dismiss);main(()->{try{darkField.setBoolean(a,priorDark);}catch(Exception e){throw new RuntimeException(e);}});a.getSharedPreferences("settings",0).edit().putString("theme",priorTheme).commit();
        Bitmap exifSource=Bitmap.createBitmap(80,40,Bitmap.Config.ARGB_8888);File exifFile=new File(a.getCacheDir(),"test-exif.jpg");try(FileOutputStream o=new FileOutputStream(exifFile)){exifSource.compress(Bitmap.CompressFormat.JPEG,90,o);}exifSource.recycle();android.media.ExifInterface exif=new android.media.ExifInterface(exifFile.getPath());exif.setAttribute(android.media.ExifInterface.TAG_ORIENTATION,"6");exif.saveAttributes();Bitmap oriented=(Bitmap)call(Class.forName("cn.lut.schedule.BackgroundCrop"),"decode",new Class<?>[]{byte[].class},java.nio.file.Files.readAllBytes(exifFile.toPath()));check(oriented.getWidth()==40&&oriented.getHeight()==80,"phone photo EXIF rotation respected");oriented.recycle();exifFile.delete();
        invoke(a,"showBackgroundCrop",new Class<?>[]{byte[].class},bytes.toByteArray());Dialog saveDialog=(Dialog)field(a,"backgroundCrop");View confirm=text(saveDialog.getWindow().getDecorView(),"使用");main(confirm::performClick);check(background.exists()&&field(a,"background") instanceof Bitmap&&!saveDialog.isShowing(),"confirmation atomically saves and updates home");Thread.sleep(4000);invoke(a,"navigate",new Class<?>[]{int.class},0);capture("v017-home-wallpaper.png");
        Thread.sleep(8000);invoke(a,"navigate",new Class<?>[]{int.class},0);capture("v017-home-wallpaper.png");invoke(a,"navigate",new Class<?>[]{int.class},1);capture("v017-academic-services.png");invoke(a,"navigate",new Class<?>[]{int.class},2);capture("v017-settings.png");
        background.delete();invoke(a,"loadBackground",none);invoke(a,"navigate",new Class<?>[]{int.class},0);invoke(a,"renderPage",new Class<?>[]{boolean.class},false);
        return "PASS: "+checks+" v017 integration assertions: 23 official direct routes, hidden portal card links, complete grade pagination, exam publication/time handling, real timetable path and automatic calendar, full screen WebView, automatic login routing, crop aspect/export/no empty edges/cancel/save/bitmap release";
    }
}
