plugins { id 'com.android.application' }
android {
    namespace 'cn.lut.schedule'
    compileSdk 37
    defaultConfig { applicationId 'cn.lut.schedule'; minSdk 26; targetSdk 36; versionCode 9; versionName '0.1.8-preview' }
    buildTypes { release { minifyEnabled true; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
